### PR TITLE
Api v3

### LINKED ISSUE #43: Migrate the toolbox to siibra-api v3.
As a next step I suggest to migrate the toolbox to the latest siibra-api version and do some clean-ups to have the API calls at a few well documented places in the code. Most of other issues will become much easier afterwards.

### PR DESCRIPTION
**Pull request by valentin-pinkau**
This PR adapts the siibralab client to use the v3 api only.
All previous concepts like atlases, parcellations, and so forth are supported as well as previously broken features like receptor densities or streamline counts.
This closes #43

### CODE REVIEW

**Comment by valentin-pinkau** [comment]
Hey @vijayiyer05,
Thank you for looking into this! This was indeed a regression and I fixed it. It seems the matlab function now wants a color map for the overlay.
Please have a look again :)

**Comment by vijayiyer05** [comment]
Thank you @valentin-pinkau  for the update. I I can see the more completed output on the rendered live script, which is great to see. 

However I still receive the same warning:

> Warning: The HTMLSource may be referencing unsupported functionality or may have a JavaScript error. Refer to the [documentation]( https://www.mathworks.com/help/matlab/ref/uihtml.html) for known limitations. 

When you run through the live script, are you doing this locally or on MATLAB Online? If you are having success running it through fully on MATLAB Online, I'd appreciate a short video screenshot, to help me dig into why I'm getting a different result. 

If you were running only locally, and finding it fails similarly on MATLAB Online (just need to click the badge, accept, and hit play), then I'd be curious to see if you notice the code running up against of those listed [known limitations](https://www.mathworks.com/help/matlab/ref/uihtml.html#mw_d8fc1e12-fa02-43b8-bfaa-db9dd0f2c8dd).

**Comment by vijayiyer05** [comment]
**Further testing/review notes**

For the step-by-step examples: I currently run into errors on 1.3 & 1.6. The others all run through (leaving aside those which are notes-only). 

On the toolbox side:  I notice that in `siibra.internal.API` that some of the methods have been updated to use the V3 endpoint, but others (e.g., 'featuresPageForParcellation' and most/all thereafter). Is this by design or were some missed accidentally? It seems to have stopped midway.

**Comment by valentin-pinkau** [comment]
I ran the walkthrough locally without any error or warning.
1.3 and 1.6 run through without an error for me locally.
You are right, the implementation of the features is not compatible with the v3 of the api.
I adapted the implementation to fetch all features for a region with the v3 of the api. I managed to find a region where it works, but on others it does not. So it seems that the api is not stable, as I get 500 errors when fetching the features for some regions. Also requesting tabular data resulted in 500 errors. I would suggest to leave the features part until the api is stable. What do you think?

These are the URLs I tried, which gave me 500 errors: 
* Receptor Densities for region Area hOc1 (V1, 17, CalcS): https://siibra-api-stable.apps.hbp.eu/v3_0/feature/Tabular/e715e1f7-2079-45c4-a67f-f76b102acfce--0a360d3912ff7fbbab93378e4458c1fe?parcellation_id=minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290&region_id=Area%20hOc1%20%28V1%2C%2017%2C%20CalcS%29
* All features for region Area hOc1 (V1, 17, CalcS) left: https://siibra-api-stable.apps.hbp.eu/v3_0/regions/Area%20hOc1%20(V1,%2017,%20CalcS)%20left/features?parcellation_id=minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290&page=1

**Comment by vijayiyer05** [comment]
Thank you @valentin-pinkau  for explaining why siibraLab is in a quantum state, so to speak, between APIs 2 & 3. 

 It woudl be ideal to capture this v3 gap as an Issue (for the future), say with an "api" label to indicate suspicion that root cause may be on API side. 

Can you take a try at authoring that Issue? Ideally with a test indicated that would help to determine if it were resolved in the future. For instance, if those two error-prone API calls are invoked by one or more of the step-by-step guides, they could be mentioned. Alternatively, it could be in a tests folder script (if not already). 

In the meanwhile, I'll write up an Issue to capture the MATLAB Online gap I see. 

I wonder if those

**Comment by xgui3783** [comment]
Apologies. I will investigate why some of these are returning 500 =/

**Comment by vijayiyer05** [comment]
Thank you for the update @xgui3783. Keep us posted! 

I've tested out the examples locally on my machine, and have the following insights/puzzles:

- For the walkthrough, the orthoslice view (line 25) still doesn't show the labeled region in the volume view. See window on my desktop below. Do you see a volume label (i.e., via transparency) on either of your ends? 
- I miswrote earlier: it's 1.4 & 1.6 that fail for me. This also happens for me locally. 
- I'm a bit puzzled that the endpoints in `siibralab.internal.API` differ in their trailing slash treatment. Is this intended? It does seem to affect the URLs (e.g., I get a 504 w/ the slash added and a 500 without it on step-by-step 1.6). 

One thing I wonder is if testing on your end(s) may be getting scrambled because previous class code is still being run. Often I I do a defensive `clear classes` after a class change. It's definitely less needed recently, but given these are Constant properties, they may need this at every update.

**Comment by xgui3783** [comment]
> I ran the walkthrough locally without any error or warning. 1.3 and 1.6 ran through without an error for me locally. You are right, the implementation of the features is not compatible with the v3 of the api. I adapted the implementation to fetch all features for a region with the v3 of the api. I managed to find a region where it works, but on others it does not. So it seems that the api is not stable, as I get 500 errors when fetching the features for some regions. Also requesting tabular data resulted in 500 errors. I would suggest to leave the features part until the api is stable. What do you think?
> 
> These are the URLs I tried, which gave me 500 errors:
> 
> * Receptor Densities for region Area hOc1 (V1, 17, CalcS): https://siibra-api-stable.apps.hbp.eu/v3_0/feature/Tabular/e715e1f7-2079-45c4-a67f-f76b102acfce--0a360d3912ff7fbbab93378e4458c1fe?parcellation_id=minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290&region_id=Area%20hOc1%20%28V1%2C%2017%2C%20CalcS%29
> * All features for region Area hOc1 (V1, 17, CalcS) left: https://siibra-api-stable.apps.hbp.eu/v3_0/regions/Area%20hOc1%20(V1,%2017,%20CalcS)%20left/features?parcellation_id=minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290&page=1

rejoice!

I updated added more memory, I think these issues should be resolved. 

(note, however, `GET /v3_0/regions/{REGION_NAME}/features` is quite slow on first run (cache miss)

**Comment by vijayiyer05** [comment]
That's great news @xgui3783! 

Unofortunately, I still get an error on 1.6 at line 8, with a 500 error against this query: 

> https://siibra-api-stable.apps.hbp.eu/v3_0/atlases/juelich/iav/atlas/v1.0.0/1/parcellations/minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290/regions/Area%20hOc1%20(V1,%2017,%20CalcS)%20left?space_id=minds/core/referencespace/v1.0.0/7f39f7be-445b-47c0-9791-e971c0b6d992.

How does this query work in your hands? 

Also, I shoudl have corrected, not just later clarified: it's 1.4 (not 1.3) that gave me trouble before. I've just re-tested that and it's still failing on the fuzzy matching operation (see error below 👇🏼). Any ideas on this? 

image

**Comment by xgui3783** [comment]
I will investigate. Thanks for bringing this to me attention.

**Comment by vijayiyer05** [comment]
I will add that the 2 queries noted by @valentin-pinkau DO now work. So perhaps that allows him to go further on the client side! 
Please both note the small PR #48 I've just added (and the importance of using `clear classes` after any such Constant changes)

**Comment by xgui3783** [comment]
> Unofortunately, I still get an error on 1.6 at line 8, with a 500 error against this query:
> 
> > https://siibra-api-stable.apps.hbp.eu/v3_0/atlases/juelich/iav/atlas/v1.0.0/1/parcellations/minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290/regions/Area%20hOc1%20(V1,%2017,%20CalcS)%20left?space_id=minds/core/referencespace/v1.0.0/7f39f7be-445b-47c0-9791-e971c0b6d992.

I believe the v3 API has been changed. it is now:

```
GET /v3_0/regions/{region_name}?parcellation_id={parcellation_id}&space_id={space_id}
```

e.g. 

```
curl 'https://siibra-api-stable.apps.hbp.eu/v3_0/regions/Area%20hOc1%20%28V1%2C%2017%2C%20CalcS%29%20left?parcellation_id=minds%2Fcore%2Fparcellationatlas%2Fv1.0.0%2F94c1125b-b87e-45e4-901c-00daee7f2579-290&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2F7f39f7be-445b-47c0-9791-e971c0b6d992'
```

seems to return a JSON object (n.b. of a different shape!)

**Comment by vijayiyer05** [comment]
Thank you @xgui3783. I do see a valid return for that query! 
@valentin-pinkau, can you see a path to tweak step-by-step 1.6 and/or its underlying library code to generate/use that query?

**Comment by valentin-pinkau** [comment]
@xgui3783 Thank you for increasing the memory limits so the queries run through!
I switched the features (receptor densities and streamline counts) to the new api as well.
To test them I added a section in the walkthrough live script.

@vijayiyer05 I re-ran all the step by step guides and the walkthrough without an error except for 2.4. 
@xgui3783 In 2.4, I get a 500 error requesting https://siibra-api-stable.apps.hbp.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588 is this expected? I currently handle this error as if the space does not have a resampled template for the given parcellation.

@vijayiyer05 Here, the error lies in hOc1, try a big O instead of a zero (0).
Screenshot 2024-12-16 at 15 53 51

The region in template visualization works for me:
Screenshot 2024-12-16 at 15 56 06

Please have another look :)

**Comment by vijayiyer05** [comment]
Thank you @valentin-pinkau, confirming that the walkthrough visualization now works for me too.. Great to see! 

For the walkthrough, I wonder if there's anything that can be added that creates a palpable output in the last live script section besides just returning the receptor densities object. Perhaps a histogram of the Fingerprints table data? Something else? 

The one live script I'm having an issue with is 2.4, with the error below

Though this error remains, this branch is now in a better working state than the current commit on default branch. 

So I encourage @dickscheid  or @xgui3783  to **merge this**  _without yet closing #43_,. This will allow me/others to further test on MATLAB Online (since: badges use latest commit on the default branch), while still looking at error for 2.4 and possible

image

**Comment by valentin-pinkau** [comment]
> For the walkthrough, I wonder if there's anything that can be added that creates a palpable output in the last live script section besides just returning the receptor densities object. Perhaps a histogram of the Fingerprints table data? Something else?

I think this is something, where @SBludau or @dickscheid could sway in. I don't know what the applications are and what makes sense here.

@vijayiyer05 

> The one live script I'm having an issue with is 2.4, with the error below

Yes, this is due to the failing query: https://siibra-api-stable.apps.hbp.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588 
See my comment above: https://github.com/FZJ-INM1-BDA/siibralab/pull/46#issuecomment-2545867086

**Comment by vijayiyer05** [comment]
Thank you @valentin-pinkau for deferring re the output & explaining re 2.4 error (I missed your update, sorry)

**Comment by xgui3783** [comment]
> @xgui3783 In 2.4, I get a 500 error requesting https://siibra-api-stable.apps.hbp.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588 is this expected? I currently handle this error as if the space does not have a resampled template for the given parcellation.

I found the issue, and will push the fix along with the other known issue (region with same ID)

I should specify that: you will need to query the left and right hemisphere separately (we have updated the data source to separate the hemisphere). 

(n.b. following targets rc build (i.e. https://siibra-api-rc.apps.tc.humanbrainproject.eu , but will be updated this week, if not tomorrow)

I will update this issue when it happens.

e.g. 

```bash
$ curl -v 'https://siibra-api-rc.apps.tc.humanbrainproject.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588'

// truncated for brevity
< HTTP/2 500
// truncated for brevity
{"detail":"Some error occurred","error":"Requested fragment '' could not be matched uniquely to [left hemisphere, right hemisphere]"}
```

but

```
$ curl -v 'https://siibra-api-rc.apps.tc.humanbrainproject.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588&name=left%20hemisphere'

// truncated for brevity
< HTTP/2 200
< date: Tue, 17 Dec 2024 14:33:38 GMT
< content-type: application/octet-stream
< content-length: 205269
// truncated for brevity
Warning: Binary output can mess up your terminal. Use "--output -" to tell ...
```

**Comment by xgui3783** [comment]
@valentin-pinkau 

I have pushed the new version of api, which should fix the resample template issue:

```
$ curl -v 'https://siibra-api.apps.ebrains.eu/v3_0/map/resampled_template?parcellation_id=juelich%2Fiav%2Fatlas%2Fv1.0.0%2F3&space_id=minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fa1655b99-82f1-420f-a3c2-fe80fd4c8588&name=left%20hemisphere' 
// truncated for brevity
< HTTP/2 200
// truncated for brevity
Warning: Binary output can mess up your terminal. Use "--output -" to tell ...
```

---

I can't find the issue where region may have multiple IDs. This should also be resolved in the current api (for bundle parcellations, we effectively flattened the region tree, and only kept the leaf nodes). 

there are a few other regions (in waxholm rat, for example, in one of the branch node, in juelich brain <= 2.9, leaf node CH 123 {left,right} hemisphere appear multiple times, for example). I understand these should be less problematic.

**Pull request merged**
